In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder

In [ ]:
data = pd.read_csv('Student_marks.csv')

In [ ]:

X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values
print(X)

[[ 1 78 85 90 75]
 [ 2 85 80 92 88]
 [ 3 92 88 78 90]
 [ 4 65 75 85 80]
 [ 5 78 92 88 85]
 [ 6 88 85 90 92]
 [ 7 75 80 78 70]
 [ 8 90 92 85 88]
 [ 9 82 78 75 80]
 [10 95 90 88 92]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[ 0.  0.  0.  0.  1.  0.  1. 78. 85. 75.]
 [ 0.  0.  0.  0.  0.  1.  2. 85. 80. 88.]
 [ 0.  1.  0.  0.  0.  0.  3. 92. 88. 90.]
 [ 0.  0.  1.  0.  0.  0.  4. 65. 75. 80.]
 [ 0.  0.  0.  1.  0.  0.  5. 78. 92. 85.]
 [ 0.  0.  0.  0.  1.  0.  6. 88. 85. 92.]
 [ 0.  1.  0.  0.  0.  0.  7. 75. 80. 70.]
 [ 0.  0.  1.  0.  0.  0.  8. 90. 92. 88.]
 [ 1.  0.  0.  0.  0.  0.  9. 82. 78. 80.]
 [ 0.  0.  0.  1.  0.  0. 10. 95. 90. 92.]]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
multi_linear_model = LinearRegression()
multi_linear_model.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred_multi_linear = multi_linear_model.predict(X_test)